# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce330daaf370a06a90598ff721933a3f8984e26236e13b7d9fdf98da15fd44e491bff975a8ab4102faf43241cad49c5261d86540e3ec7429de0b4e18f4d304cb

test:
  secret_key_base: c317858f48cf4e0e5245ad4075690f9f3c28897b13d8b0dd776e15fd32192fbfc425cb0d82e66d4d472a6cc6b1adc28ca4869f0937c967e8ec055bf54e4322de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
